name: admin-ui-callpermission
namespace: official
version: 1.0.0-1
author: Wazo Team
display_name: Callpermissions
min_wazo_version: 18.03
tags:
  - callpermission
homepage: https://github.com/wazo-pbx/wazo-admin-ui-callpermission
depends:
  - name: admin-ui-user
    namespace: official
  - name: admin-ui-group
    namespace: official
  - name: admin-ui-outcall
    namespace: official
