name: admin-ui-call-permission
namespace: official
version: 1.0.0-1
author: Wazo Team
display_name: Call Permissions
min_wazo_version: 18.03
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-call-permission
